### ISSUE TITLE
License

### ISSUE THREAD

**Issue by webguitou** [dreamerslab/node.extend#25]
Hi,

Under what license do you distribute node.extend ? 

MIT or GNU GPL ?

**Comment by ben-lin** [comment]
There is a link on the readme https://github.com/dreamerslab/node.extend#license

**Comment by webguitou** [comment]
I saw the link. It points to MIT licence.

MIT and GNU GPL have very different conditions. So I am allowed to pick the most convenient license for me (MIT)?

**Comment by ben-lin** [comment]
I wrote this long time ago. It was dual licensed but now it's just MIT.
