### ISSUE TITLE
License "OR" or "AND"?

### ISSUE THREAD

**Issue by finalclass** [dreamerslab/node.extend#27]
Hey, In your README.md file it states that it's 

> MIT or GPL Version 2

However in the LICENSE.md file it says that it's:

> MIT and GPL2

So which is true? The "OR" version or the "AND" one?

Could you change the "LICENSE.md" file to have the "OR" instead of "AND" because I guess this was the intention?

**Comment by ljharb** [comment]
Both have the same meaning here; multiple licenses always means “or”
